name: flutter_siren
description: One way to notify users when a new version of your app is available and prompt them to upgrade.
version: '1.2.0'
homepage: https://github.com/diegocosta/flutter_siren
issue_tracker: https://github.com/diegocosta/flutter_siren/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.12
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: